on:
  pull_request:
    types: [closed]
env:
  ENV_NAME: preview
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'preview'
      - name: Set up Node environment
        run: echo .artifacts