name: Preview Deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  ENV_NAME: preview
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: v16.19.1
          registry-url: https://npm.pkg.github.com
      - name: Setup Git
        run: |
          git config user.name "xLabs Playground CI"
          git config user.email "devops@xlabs-playground.xyz"
      - name: Install dependencies
        run: npm ci
      - name: Compute Version
        id: version
        run: |
          npm version prerelease --preid $(echo ${{ github.sha }} | cut -c -10)
          echo "_PKG_VERSION=$(node -p -e "require('./package.json').version")" >> "${GITHUB_ENV}"
      - name: Build and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLIC_URL: ${_PKG_VERSION}
        run: |
          npm run build
          npm publish
      - name: Checkout ${ENV_NAME} branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.ENV_NAME }}
          path: ${{ env.ENV_NAME }}
      - name: Trigger a ${ENV_NAME} Deploy 
        run: |
          pushd ${ENV_NAME}
          echo ${_PKG_VERSION} >> .artifacts
          git config user.name "xLabs Playground CI"
          git config user.email "devops@xlabs-playground.xyz"
          git add .artifacts
          git commit -m"Update ${ENV_NAME} artifacts"
          git push
