name: Preview [Clean Up]

on:
  pull_request:
    types: [closed]

jobs:
  preview-clean-up:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: preview
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: v16.19.1
          registry-url: https://npm.pkg.github.com
      - name: Setup Git
        run: |
          git config --global user.name "xLabs Playground CI"
          git config --global user.email "devops@xlabs-playground.xyz"
      - name: Compute Version
        run: |
          echo "_BRANCH_NAME_SHA=$(echo ${{ github.event.pull_request.head.ref }} | sha256sum | cut -c -10)" >> "${GITHUB_ENV}"
      - name: Set up Node environment
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -la
          cat .npmrc
          bash scripts/unpublish.sh ${_BRANCH_NAME_SHA}
          git add ${_BRANCH_NAME_SHA}
          git commit -m"Remove preview artifacts"
          git push
