name: Preview Deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  ENV_NAME: preview
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: v16.19.1
          registry-url: https://npm.pkg.github.com
      - name: Setup Git
        run: |
          git config user.name "xLabs Playground CI"
          git config user.email "devops@xlabs-playground.xyz"
      - name: Install dependencies
        run: npm ci
      - name: Compute Version
        id: version
        run: |
          npm version prerelease --preid $(echo ${{ github.sha }} | cut -c -10)
          echo "_PKG_VERSION=$(node -p -e "require('./package.json').version")" >> "${GITHUB_ENV}"
          echo "_BRANCH_NAME_SHA=$(echo ${{ github.sha }} | sha256sum | cut -c -10)" >> "${GITHUB_ENV}"
      - name: Build and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLIC_URL: ${_PKG_VERSION}
        run: |
          npm run build
          npm publish
      - name: Checkout preview branch
        uses: actions/checkout@v3
        with:
          ref: preview
          path: preview
      - name: Trigger a preview Deploy 
        run: |
          git config user.name "xLabs Playground CI"
          git config user.email "devops@xlabs-playground.xyz"
          mkdir -p preview/${_BRANCH_NAME_SHA}
          pushd preview/${_BRANCH_NAME_SHA}
          [[ ! -f .latest ]] && touch .latest
          [[ ! -f .artifacts ]] && touch .artifacts
          cat .latest >> .artifacts
          echo ${_PKG_VERSION} > .latest
          git add .artifacts .latest
          git commit -m"Update preview artifacts"
          git push
