name: Preview Deployment
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: v16.19.1
          registry-url: https://npm.pkg.github.com
      - name: Setup Git
        run: |
          git config user.name "xLabs Playground CI"
          git config user.email "devops@xlabs-playground.xyz"
      - name: Build and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm version prerelease --preid $(echo ${{ github.sha }} | cut -c -10)
          npm publish
      - name: Checkout preview branch
        uses: actions/checkout@v3
        with:
          ref: preview
          path: preview
      - name: Deploy
        run: node --print 'require("./package.json").version' >> preview/.artifacts
      - name: Setup Git
        run: |
          pushd preview
          git config user.name "xLabs Playground CI"
          git config user.email "devops@xlabs-playground.xyz"
          git add .artifacts
          git commit -m"Update preview artifacts"
          git push
